---
# tasks file for update-sshd-config
- name: update /etc/hosts entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: 127.0.0.1 localhost poc-check-deployment

- name: Disable X11Forwarding parameter
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11Forwarding'
    line: X11Forwarding no

- name: Disable PermitRootLogin parameter
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^\#PermitRootLogin'
    line: PermitRootLogin no

- name: Disable PasswordAuthentication parameter
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: PasswordAuthentication no

- name: Disable ClientAliveInterval parameter
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#ClientAliveInterval'
    line: ClientAliveInterval  3600

- name: Disable ClientAliveCountMax parameter
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#ClientAliveCountMax'
    line: ClientAliveCountMax  1

- name: Restart service sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
