---
# tasks file for set-motd
- name: set motd
  template:
    src: files/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0444

- name: disable default dynamic motd
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sshd
    regexp: 'motd\=\/run\/motd.dynamic'
    line: motd=/etc/motd
