---
#- hosts: all:!~build-*:!~cleura-build-*:!~yocto-build-*
#- hosts: all:!*build-*
- hosts: 10.1.0.20
  gather_facts: true
  become: true
  tasks:
  - name: print hostname
    debug:
      msg: "Hostname: {{ ansible_hostname }}"