---
# - hosts: selfservice_demo_group
- hosts: 10.101.1.244
  gather_facts: false
  become: true

  roles:
    - set-motd
    - disable-users
    - create-user-with-sudo
    - update-repos
    - update-sshd-config
    - update-cron-permission
    - update-etcfiles-permission
    - install-packages