---
- hosts: selfservice_demo_group
  gather_facts: true
  become: true

  roles:
    - set-motd
    - disable-users
    - create-user-with-sudo
    - update-repos
    - update-sshd-config
    - update-cron-permission
    - update-etcfiles-permission
    - install-packages