---
# tasks file for update-etcfiles-permission
- name: Change etc files ownership, group and permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ files }}"
