---
# tasks file for install-packages
- name: Install fail2ban package
  ansible.builtin.apt:
    name: fail2ban
    state: present
    force: true
    install_recommends: true
    update_cache: true
  notify:
      - start and enable fail2ban service
