---
# tasks file for install-packages
- name: Add lynis apt key
  ansible.builtin.apt_key:
    url: https://packages.cisofy.com/keys/cisofy-software-public.key
    state: present
  changed_when: false

- name: Add lynis apt repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.cisofy.com/community/lynis/deb/ stable main
    state: present
  changed_when: false

- name: Install logwatch package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    force: true
    install_recommends: true
    update_cache: true
  with_items:
    - "{{ packages }}"
  register: install_status
  notify:
      - start and enable fail2ban service

- name: debug install message
  debug:
    var: install_status
