---
# tasks file for install-packages
- name: Install fail2ban package
  ansible.builtin.apt:
    name: fail2ban
    state: present
    force: true
    install_recommends: true
    update_cache: true
  notify:
      - start and enable fail2ban service

- name: Install logwatch package
  ansible.builtin.apt:
    name: logwatch
    state: present
    force: true
    install_recommends: true
    update_cache: true

- name: Install rkhunter package
  ansible.builtin.apt:
    name: rkhunter
    state: present
    force: true
    install_recommends: true
    update_cache: true

- name: Add lynis apt key
  ansible.builtin.apt_key:
    url: https://packages.cisofy.com/keys/cisofy-software-public.key
    state: present
  changed_when: true

- name: Add lynis apt repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.cisofy.com/community/lynis/deb/ stable main
    state: present
  changed_when: true

- name: Install lynis package
  ansible.builtin.apt:
    name: lynis
    state: present
    force: true
    install_recommends: true
    update_cache: true