---
# tasks file for install-packages
- name: Add lynis apt key
  ansible.builtin.apt_key:
    url: https://packages.cisofy.com/keys/cisofy-software-public.key
    state: present

- name: Add lynis apt repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.cisofy.com/community/lynis/deb/ stable main
    state: present

- name: Install logwatch package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    force: true
    install_recommends: true
    update_cache: true
  with_items:
    - "{{ packages }}"

- name: start and enable fail2ban service
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
