---
# tasks file for disable-users
- name: disable user accounts
  ansible.builtin.user:
    name: "{{ item }}"
    state: present
    password_lock: true
    shell: "/sbin/nologin"
  with_items:
    - "{{ users_list }}"