---
# tasks file for create-user-with-sudo
- name: Create user account
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
  with_items:
    - "{{ users_list }}"

- name: Update User with sudo privilege
  ansible.builtin.blockinfile:
    path: /etc/sudoers.d/90-cloud-init-users
    block: |
      # User rules for "{{ item }}"
      "{{ item }}" ALL=(ALL) NOPASSWD:ALL
  with_items:
    - "{{ users_list }}"
